FileVersion = 1

[Project]
Name = "Sedulous.Textures.Importer"
TargetType = "BeefLib"

[Dependencies]
corlib = "*"
"Sedulous.Images" = "*"
"Sedulous.Images.IO" = "*"
"Sedulous.Textures" = "*"
"Sedulous.Textures.Resources" = "*"
"Sedulous.Resources" = "*"
"Sedulous.Serialization" = "*"
