FileVersion = 1

[Project]
Name = "Sedulous.UI2"
TargetType = "BeefLib"
StartupObject = "Sedulous.UI2.Program"

[Dependencies]
corlib = "*"
"Sedulous.Core" = "*"
"Sedulous.Core.Mathematics" = "*"
"Sedulous.VG" = "*"
"Sedulous.Fonts" = "*"
"Sedulous.Images" = "*"
"Sedulous.VG.SVG" = "*"
