FileVersion = 1

[Project]
Name = "UI2Sandbox"
StartupObject = "UI2Sandbox.Program"

[Dependencies]
corlib = "*"
"Sedulous.UI2" = "*"
"Sedulous.UI2.Runtime" = "*"
"Sedulous.Runtime.Client" = "*"
"Sedulous.Runtime" = "*"
"Sedulous.Core.Mathematics" = "*"
"Sedulous.RHI" = "*"
"Sedulous.Shell" = "*"
"Sedulous.Images.STB" = "*"
"Sedulous.Images.SDL" = "*"
"Sedulous.Fonts" = "*"
"Sedulous.Fonts.TTF" = "*"
