FileVersion = 1

[Project]
Name = "Sedulous.UI2.Tests"
TargetType = "BeefTest"
StartupObject = "Sedulous.UI2.Tests.Program"

[Dependencies]
corlib = "*"
"Sedulous.UI2" = "*"
"Sedulous.Core.Mathematics" = "*"
"Sedulous.Images" = "*"
"Sedulous.UI2.Toolkit" = "*"
