FileVersion = 1

[Project]
Name = "Sedulous.UI2.Runtime"
TargetType = "BeefLib"
StartupObject = "Sedulous.UI2.Runtime.Program"

[Dependencies]
corlib = "*"
"Sedulous.UI2" = "*"
"Sedulous.UI2.Shell" = "*"
"Sedulous.Runtime" = "*"
"Sedulous.Core" = "*"
"Sedulous.Core.Mathematics" = "*"
"Sedulous.VG" = "*"
"Sedulous.VG.Renderer" = "*"
"Sedulous.RHI" = "*"
"Sedulous.Shell" = "*"
"Sedulous.Shaders" = "*"
"Sedulous.Fonts" = "*"
"Sedulous.Fonts.TTF" = "*"
"Sedulous.Images" = "*"
"Sedulous.Profiler" = "*"
